export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as LogIn } from "./LogIn";
export { default as PostList } from "./PostList";
export { default as SinglePost } from "./SinglePost";
export { default as Register } from "./Register";
export { default as NewPost } from "./NewPost";
export { default as MainPage } from "./MainPage";
export { default as Messages } from "./Messages";
